name: Deploy Node.js to AWS EC2

on:
  push:
    branches:
      - main  # Change this to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          cd /home/ec2-user/app  # Change path if necessary
          git pull origin main
          npm install
          npm run build  # If needed
          pm2 restart app.js  # Change to your start file
